on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    name: Run test memory
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run file command on all .jpg files
        run: |
          find . -name '*.jpg' -exec file {} \;
  build-memory:
    name: Build Docker Image
    runs-on: [self-hosted]
    needs: test-memory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print working directory
        run: |
          pwd  # Affiche le répertoire courant
          ls -l  # Liste les fichiers du répertoire courant

      - name: Build Docker image
        run: |
          docker build -t flaviiie/memory:latest .
